name: bool_dogoo
description: Simple functions and extension for boolean type.
version: 0.1.0
repository: https://github.com/Wellssi/dogoo/tree/develop/packages/common/bool_dogoo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
# dependencies:
#  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
