# Ref: https://dart.dev/tools/linter-rules/all
include: all_linter_rules.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    deprecated_member_use_from_same_package: ignore
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    parameter_assignments: warning
    todo: ignore

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_annotating_with_dynamic: false
    avoid_classes_with_only_static_members: false
    cascade_invocations: false
    comment_references: false
    library_private_types_in_public_api: false
    omit_obvious_property_types: false # make clearly declare the type
    one_member_abstracts: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_final_parameters: false # make parameter immutable
    unnecessary_final: false
