name: datetime_dogoo
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none # TODO: 배포 준비 완료 시 삭제
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  num_dogoo: # TODO: num_dogoo 선 배포 후 참조 변경
    path: ../num_dogoo

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
