name: datetime_dogoo
description: Provides simple functions and extensions for DateTime type. This is part of the 'dogoo' package that provides 'Dart' and 'Flutter' utilities.
version: 0.1.0
repository: https://github.com/Wellssi/dogoo/tree/develop/packages/common/datetime_dogoo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  num_dogoo: ^0.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
