part of 'rich_text.dart';

const String _type = 'type';
const String _annotations = 'annotations';
const String _plainText = 'plain_text';
const String _href = 'href';
const String _bold = 'bold';
const String _italic = 'italic';
const String _strikethrough = 'strikethrough';
const String _underline = 'underline';
const String _code = 'code';
const String _color = 'color';
const String _expression = 'expression';
const String _id = 'id';
const String _mention = 'mention';
const String _start = 'start';
const String _end = 'end';
const String _url = 'url';
const String _templateMentionDate = 'template_mention_date';
const String _user = 'user';
const String _content = 'content';
const String _link = 'link';
